# Generated by Django 5.0.7 on 2024-10-31 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='onboardservice',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardservice',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='core.destination'),
        ),
    ]
