# Generated by Django 5.0.7 on 2024-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_onboardservice_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='destination',
        ),
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='core.destination'),
        ),
    ]
