# Generated by Django 5.0.7 on 2024-11-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cruise_destination_cruise_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_list', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bookings',
            field=models.ManyToManyField(related_name='customer_bookings_set', through='core.CustomerBooking', to='core.booking'),
        ),
    ]
