# Generated by Django 5.0.7 on 2024-11-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customersegment_userrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
