# Generated by Django 5.0.7 on 2024-11-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usermodule_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodule',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usermodule',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='usermodule',
            name='is_employee',
        ),
    ]
